name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: [feat]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Proposed Solution
      description: How should it work? Any UI or technical details?
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to solve this?
